# Generated by Django 3.0.7 on 2020-06-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200622_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humiditysensor',
            old_name='s_name',
            new_name='s_name_id',
        ),
    ]
