# Generated by Django 3.0.7 on 2020-10-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200623_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humiditysensor',
            options={'ordering': ['s_type']},
        ),
    ]
